### ISSUE TITLE
Feature request: Verify using bom versions

### ISSUE THREAD

**Issue by warting** [F43nd1r/bomVersionCatalog#20]
This is an amazing plugin. Found it while looking for a plugin to verify and enforce bom usages.
Is there a way to enforce that the specified boms version is used and not allow modules to use hardcoded versions of the dependencies?

**Comment by F43nd1r** [comment]
That is most likely possible, but completely out of scope here. It would require a build plugin to check configurations, but this is a settings plugin - too early in the chain.
